language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.7

# See http://scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html for recommendation.
cache:
  sudo: false
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
